name: mazha_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  provider: ^6.0.5
  google_sign_in: ^6.1.4
  cloud_firestore: ^4.8.4
  shared_preferences: ^2.2.0
  rounded_loading_button: ^2.1.0
  font_awesome_flutter: ^10.4.0
  connectivity_plus: ^3.0.6
  lottie: ^2.5.0
  geolocator: ^10.0.0
  image_picker: ^1.0.4
  geocoding: ^2.1.0
  multi_image_picker_view: ^0.0.17
  mobile_number: ^2.1.1
  graphql: ^5.2.0-beta.6
  graphql_flutter: ^5.2.0-beta.3
  flutter_rating_bar: ^4.0.1
  permission_handler: ^11.0.0
  timeago: ^3.5.0
  url_launcher: ^6.1.14
  firebase_storage: ^11.2.7
  awesome_snackbar_content: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - animations/
    - assets/icons/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
